# Updated Database Configuration for Aiven MySQL
db.url=jdbc:mysql://mysql-2671b501-suraj71442-45b8.h.aivencloud.com:13931/defaultdb?ssl-mode=REQUIRED
db.user=avnadmin
# Aiven dashboard se "reveal" karke yahan apna password paste karein
db.password=${DB_PASSWORD}

# Email Config (Keep these secret!)
mail.user=dilip62897@gmail.com
mail.pass=${EMAIL_PASSWORD}
