# =================================================   
# DATABASE CONFIGURATION (AIVEN MYSQL)
# =================================================   
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-2671b501-suraj71442-45b8.h.aivencloud.com:13931/defaultdb?ssl-mode=REQUIRED
db.user=avnadmin
# Railway environment variable se link
db.password=${DB_PASSWORD}

# =================================================   
# EMAIL CONFIGURATION (GMAIL SMTP)
# =================================================   
mail.user=dilip62897@gmail.com
# Railway environment variable se link
mail.pass=${EMAIL_PASSWORD}
